coverage:
  range: 70..100
  round: down
  precision: 1

codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 3
    wait_for_ci: true

comment:
  after_n_builds: 3

github_checks:
  annotations: false
