name: pudl-zenodo-storage
channels:
  - conda-forge
  - defaults
dependencies:
  - pip>=21.0,<22
  - python>=3.8,<3.11
  - tox>=3.24,<4
  - pip:
    - git+https://github.com/catalyst-cooperative/pudl.git@dev#egg=catalystcoop.pudl
    - --editable ./[test]
