name: pudl-zenodo-storage
channels:
  - conda-forge
dependencies:
 - datapackage < 2.0
 - factory_boy < 3.0
 - pytest < 7.0
 - requests < 3.0
 - semantic_version < 3.0
 - pip>=21.0,<22
 - pip:
   - --editable=git+https://github.com/catalyst-cooperative/pudl.git@dev#egg=catalystcoop.pudl
